AWSTemplateFormatVersion: '2010-09-09'

Description: "Join all templates"
Parameters:
  VPCName:
    Description: VPC Name.
    Type: String
    Default: vpc_pro2

  BucketName:
    Description: Bucket name where the templates are located
    Type: String
    Default: https://cloudf-bucket.s3.us-east-2.amazonaws.com

Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        VPCName: !Ref VPCName
      TemplateURL: !Sub ${BucketName}/vpc.yaml
  Config:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        VPC: !GetAtt VPC.Outputs.VPCId
        DefaultSecurityGroup: !GetAtt VPC.Outputs.DefaultSecurityGroup
      TemplateURL: !Sub ${BucketName}/config.yaml
  EC2:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        PublicSubnet1: !GetAtt VPC.Outputs.PublicSubnet1
        PublicSubnet2: !GetAtt VPC.Outputs.PublicSubnet2
        SecurityGroup: !GetAtt Config.Outputs.SecurityGroup
      TemplateURL: !Sub ${BucketName}/ec2.yaml
  LB:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        PublicSubnet1: !GetAtt VPC.Outputs.PublicSubnet1
        PublicSubnet2: !GetAtt VPC.Outputs.PublicSubnet2
        EC2Web1: !GetAtt EC2.Outputs.EC2Web1
        EC2Web2: !GetAtt EC2.Outputs.EC2Web2
        SecurityGroup: !GetAtt Config.Outputs.SecurityGroup
      TemplateURL: !Sub ${BucketName}/lb.yaml